Feature
AndreiMischie/OnlineShop pull request #1
Opened 2023-07-21 14:07 UTC by AndreiMischie

2023-07-23 20:03 UTC, barbulathina requested changes

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/ShopApplication.java
> +import org.springframework.transaction.annotation.EnableTransactionManagement;
unused import, you can remove it

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/configuration/LoadDatabase.java
> +public class LoadDatabase {
are you using this config? don't push commented code

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/controller/OrdersController.java
> +        Customer customer = customerService.getCustomer(ordersDto.getCustomerId());
You should not use CustomerService here. You should move the logic inside the OrderService, as the Controller must have no business logic at all.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/controller/OrdersController.java
> +    public ResponseEntity<Object> postOrder(@RequestBody OrdersDto ordersDto){
We have a POST method here. You should return the newly created Order here.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/controller/OrdersController.java
> +    @PostMapping("/orders")
You should move the @RequestMapping value '/orders' on the controller itself, which basically will add it as a prefix for all the operations made in this controller.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/controller/ProductController.java
> +    @PostMapping("/products")
Same applies here, as in the OrdersController, add the @RequestMapping value '/products' on the controller.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/controller/ProductController.java
> +    private ProductCategoryService productCategoryService;
Delete the ProductCategoryService because you are not using it here and you also should not have it in this controller.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/controller/ProductController.java
> +    @ResponseBody
What is the benefit of using this?

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/controller/ProductController.java
> +    public ResponseEntity<Object> putProduct(@PathVariable("id") UUID id,@RequestBody ProductDto productDto) {
Return the ProductDto after updating it.  The return type should be ResponseEntity<ProductDto>. Same applies for the POST method.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/controller/ProductController.java
> +        return new ResponseEntity<>("Product created!", HttpStatus.OK);
The HTTP status should be HttpStatus.CREATED here. You can have a look here at all the codes: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/controller/OrdersController.java
> +        return new ResponseEntity<>("Order Created!", HttpStatus.OK);
This method can return the HttpStatus.CREATED.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/dto/OrdersDto.java
> +    private Address address;
**Don't use the entity in the DTO**. Either you created another DTO here, particularly for the Address, or use only the necessary fields.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/dto/OrdersDto.java
> +    private UUID customerId;
Nothing to change here, but in a real application this ID would come from an authentication token. In Chapter 5 we don't need the customerId in the DTO.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/dto/ProductQuantityPair.java
> +public class ProductQuantityPair {
You should add the suffix DTO to this entity.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/entity/Customer.java
>  @EqualsAndHashCode(callSuper = true)
Make a habit of formatting your code. You can use CTRL+ALT+L in IntelliJ.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/entity/BaseClass.java
>  public class BaseClass {
BaseClass can be abstract. We have this one class to provide a common definition for the other entities.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/entity/Customer.java
>  @EqualsAndHashCode(callSuper = true)
@EqualsAndHashCode is included in @Data. You can remove it from here. The same applies to the other entity classes.
https://projectlombok.org/features/Data

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/entity/OrderDetailId.java
> +    private Location shippedFrom;
Is this field part of the composite id? You should remove it.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/entity/OrderDetail.java
> +    private Location shippedFrom;
The Location should not be part of the composite id for OrderDetail.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/mapper/OrdersMapper.java
> +    @Mapping(source = "customer",target = "customer")
No need to declare the source and target if they have the same name and we have only one source.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/mapper/ProductMapper.java
> +    Product toProduct(ProductDto productDto);
Is this working correctly?

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/entity/OrderDetailId.java
>  public class OrderDetailId implements Serializable {
You can place your composite ids in another package. It should be a subpackage of _ro.msg.learning.shop.entity_.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/repository/OrderDetailRepository.java
> +public interface OrderDetailRepository extends JpaRepository<OrderDetail, UUID> {
Your ID should be OrderDetailId.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/repository/ProductCategoryRepository.java
> +    Optional<ProductCategory> findById(UUID id);
You don't need to define this method here, it comes out of the box with the JpaRepository.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/repository/StockRepository.java
> +import java.util.UUID;
Unused import, remove it. You should make a habit of removing the unused imports. Try CTRL+ALT+O in IntelliJ.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/service/OrderDetailService.java
> +    public abstract void createOrderDetail(OrderDetail orderDetail);
**abstract** is redundant in this case. Methods declared in interfaces are by default public & abstract. The same applies to OrdersService, StockService and ProductService.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/service/ProductCategoryService.java
> +//      void createProductCategory(ProductCategory product);
Don't push commented code. Remove it.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/service/impl/CustomerServiceImpl.java
> +    public Customer getCustomer(UUID id){
Let the method breathe. Put an empty line between.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/service/impl/OrderDetailServiceImpl.java
> +    public void createOrderDetail(OrderDetail orderDetail){
You should return the newly created OrderDetail here.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/service/impl/OrdersServiceImpl.java
> +            throw new RuntimeException();
Define a custom exception that extends RuntimeException.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/service/impl/ProductCategoryServiceIpml.java
> +public class ProductCategoryServiceIpml implements ProductCategoryService {
You have a small typo here.

2023-07-23 20:03 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/service/impl/ProductServiceImpl.java
> +    @Override
Let the methods breathe. Format your code.

2023-07-23 20:03 UTC, barbulathina commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=none
You should use the value **_validate_** here. https://docs.jboss.org/hibernate/orm/6.2/userguide/html_single/Hibernate_User_Guide.html#configurations-hbmddl

2023-07-23 20:03 UTC, barbulathina commented on src/main/resources/db/migration/V0__create_tables_schema.sql
> +create table customer (id uuid not null default uuid_generate_v4(), email_address varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), username varchar(255), primary
Style your SQL files. The SQL-reserved keywords need to be written in uppercase. Have a look here https://www.sqlstyle.guide/.

2023-07-24 05:47 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/service/impl/CustomerServiceImpl.java
> +    @Autowired
You should better use constructor injection here. Sometimes field injection is ambiguous, while constructor-based injection enforces the dependency requirement. It has more advantages than field injection. You can do this with Lombok's **@RequiredArgsConstructor** annotation. Please adapt this wherever this situation occurs.
https://mohamed-kashif.medium.com/constructor-injection-vs-field-injection-in-java-2265200fe203
https://www.baeldung.com/spring-injection-lombok

2023-07-24 15:36 UTC, barbulathina commented on src/test/java/ro/msg/learning/shop/ShopApplicationTests.java
> +//package ro.msg.learning.shop;
don't push commented code

2023-07-24 15:36 UTC, barbulathina commented on src/main/resources/db/migration/V0__create_tables_schema.sql
> +create table customer (
you forgot one here to style :)

2023-07-24 15:40 UTC, barbulathina commented on src/main/java/ro/msg/learning/shop/service/impl/OrderNotCreatedException.java
> +package ro.msg.learning.shop.service.impl;
You should move this class into a different package.

2023-07-25 07:15 UTC, AndreiSold commented on src/test/java/ro/msg/learning/shop/ShopApplicationTests.java
> +//package ro.msg.learning.shop;
@AndreiMischie let's solve the remaining comments so that we can merge this PR

2023-07-25 07:15 UTC, AndreiSold commented on src/main/resources/db/migration/V0__create_tables_schema.sql
> +create table customer (
Don't forget to style this file

2023-07-25 07:16 UTC, AndreiSold commented on src/main/java/ro/msg/learning/shop/service/impl/OrderNotCreatedException.java
> +package ro.msg.learning.shop.service.impl;
For custom exceptions you should have a separate folder in the root part of your project called `exceptions` , let's do this

2023-07-25 07:54 UTC, barbulathina approved these changes
ok

2023-07-25 07:54 UTC, merged